# This file was generated by GoReleaser. DO NOT EDIT.
class KubeBootstrap < Formula
  desc "Bootstrap your laptop for Kubernetes"
  homepage ""
  version "0.0.2"

  if OS.mac?
    url "https://github.com/discreet/kube-bootstrap/releases/download/v0.0.2/kube-bootstrap-v0.0.2-darwin-amd64.tar.gz"
    sha256 "e27397dc898e19340e463bd7d68f45c545dded2e69b93813afdd674171734f27"
  elsif OS.linux?
  end

  def install
    bin.install "kube-bootstrap"
  end

  test do
    system "#{bin}/kube-bootstrap --version"
  end
end
